### PR TITLE
Optimizing Gas Usage

### PR DESCRIPTION
**Pull request by anthonjn**
Ongoing PR for optimizations. 

One change was updating uint8 -> uint256. Going off a hunch that uint8 has some inefficiencies compared to 256 since the EVM uses 32bytes as a base which means there is more optcode to be doing w/ relation to uint8 vs 256. These were three tests that came up with gas savings as seen below (assuming `forge` gas usage is correct)
```
[PASS] testCC0Mint() (gas: 496421, new_gas: 494693, diff: 1728)
[PASS] testRerollTrait() (gas: 639978, new_gas: 638224, diff: 1754)
[PASS] testRerollTraitCost() (gas: 715911, new_gas: 714105, diff: 1806)
```

Second major change is tight packing. Using tight packing during the creation of, was able to squeeze out a few more gas gains. (Not 100% sure why there was actually an increase in gas usage from testPublicMintRevert, by 17. But will look into it). New changes + changes above result in these gas diffs
```
testBatchSummon() (
    gas: 825791, new_gas: 804794, diff: 20997, percentage_delta: 2.5426530441721935
)
testBurn() (
    gas: 459084, new_gas: 442259, diff: 16825, percentage_delta: 3.6649066401791393
)
testSummon() (
    gas: 766699, new_gas: 745702, diff: 20997, percentage_delta: 2.73862363195987
)
testAllowListMint() (
    gas: 291828, new_gas: 272746, diff: 19082, percentage_delta: 6.538783118823417
)
testAllowListMintRevertInvalidSig() (
    gas: 58766, new_gas: 39684, diff: 19082, percentage_delta: 32.47115679134193
)
testAllowListMintRevertNotActive() (
    gas: 45763, new_gas: 28681, diff: 17082, percentage_delta: 37.32709831086249
)
testAllowListMultipleMintRevert() (
    gas: 294538, new_gas: 275462, diff: 19076, percentage_delta: 6.476583666623662
)
testBasePrice() (
    gas: 338416, new_gas: 319340, diff: 19076, percentage_delta: 5.636849321545081
)
testBurn() (
    gas: 268620, new_gas: 253355, diff: 15265, percentage_delta: 5.6827488645670465
)
testCC0Mint() (
    gas: 496421, new_gas: 475251, diff: 21170, percentage_delta: 4.264525473338154
)
testCc0ListMultipleMintRevert() (
    gas: 297139, new_gas: 278063, diff: 19076, percentage_delta: 6.419891027431605
)
testCc0MintRevertInvalidSig() (
    gas: 58827, new_gas: 39745, diff: 19082, percentage_delta: 32.43748618831489
)
testCc0MintRevertNotActive() (
    gas: 45724, new_gas: 28642, diff: 17082, percentage_delta: 37.358936226051966
)
testMintPrice() (
    gas: 611006, new_gas: 591998, diff: 19008, percentage_delta: 3.1109350808339036
)
testOrbsDripping() (
    gas: 606101, new_gas: 589052, diff: 17049, percentage_delta: 2.8128975203802664
)
testPublicMint() (
    gas: 463926, new_gas: 446877, diff: 17049, percentage_delta: 3.6749395377711105
)
testPublicMintRevert() (
    gas: 17482, new_gas: 17499, diff: -17, percentage_delta: -0.09724287838920032
)
testRerollTrait() (
    gas: 639978, new_gas: 620810, diff: 19168, percentage_delta: 2.995102956664135
)
testRerollTraitCost() (
    gas: 715911, new_gas: 696681, diff: 19230, percentage_delta: 2.6860880751937044
)
testRerollTraitRevert() (
    gas: 463423, new_gas: 446374, diff: 17049, percentage_delta: 3.678928322504494
)
testTeamMint() (
    gas: 2788959, new_gas: 2788959, diff: 0, percentage_delta: 0.0
)
```

### CODE REVIEW

**Comment by 0xBeans** [comment]
Thanks for the PR! Do you mind pulling from master first?

**Comment by 0xBeans** [comment]
Thanks for the PR! Do you mind pulling from master first?

**Comment by anthonjn** [comment]
Updated the branch with master.

**Comment by 0xBeans** [comment]
Nice, DM your wallet or ping me in discord you address :) Ill send ya a free scroll for this!

**Pull request merged**
