### PR TITLE
Use Custom Errors

### PR DESCRIPTION
**Pull request by 0xwuchuan**
Small gas optimisation to reduce deployment cost by using custom errors in MirakaiHeroes.sol and MirakaiScrolls.sol

### CODE REVIEW

**Comment by 0xBeans** [comment]
Thanks for the PR! Do you mind pulling from master first?

**Comment by 0xBeans** [comment]
Thanks for the PR! Do you mind pulling from master first?

**Comment by 0xwuchuan** [comment]
Done. I think Saw-mon-and-Natalie has already included this same change though

**Comment by 0xBeans** [comment]
yep I think its already in the repo, ill close this :)

I appreciate the PR tho! Check your role ;)

**Pull request closed without merging**
